config/routes.rb
Rails.application.routes.draw do
  
  resources :cities
  
  resources :team
  
  resources :user
  
  resources :contact
  
  resources :welcome
  
  resources :gossips 
  
  resources :gossips do 
  	resources :comments 
  end
  
  resources :sessions, only:[:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  # 1-N association with users table
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  # 1-N associations with user
  belongs_to :user

  # 1-N polymorphic association with comment and gossip
  belongs_to :commentable, polymorphic: true # can be associated to anything commentable
  has_many :comments, as: :commentable # is something commentable

  # 1-N associations with likes
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title, presence: true, length: {in: 3..50}
  validates :content, presence: true
  
  # 1-N association with users table
  belongs_to :user

  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with tags table via the gossip_meta table
  has_many :tags, through: :gossip_meta

  # 1-N polymorphic association with comments as commentable
  has_many :comments, as: :commentable

  # 1-N associations with likes
  has_many :likes
end

app/models/gossip_metum.rb
# the join table that maps the N-N association between gossips and tags
class GossipMetum < ApplicationRecord
  # 1-N association with gossips table
  belongs_to :gossip

  # 1-N association with tags table
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  # 1-N associations with users, gossips and comments
  belongs_to :user
  # can apply to a gossip or a comment
  belongs_to :gossip, optional: true if :comment_id
  belongs_to :comment, optional: true if :gossip_id
end

app/models/message_delivering.rb
# the join table that maps the N-N association between recipients and received_messages
class MessageDelivering < ApplicationRecord
  # 1-N association with recipients (users) table
  # class_name tells rails recipient is a user
  belongs_to :recipient, class_name: 'User'

  # 1-N association with received_messages (private_messages) table
  # class_name tells rails received_message is a private_message
  belongs_to :received_message, class_name: 'PrivateMessage'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  # 1-N association with senders (users) table
  belongs_to :sender, class_name: 'User'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :received_message_id

  # N-N association with recipients (users) table via message_deliverings table
  has_many :recipients, through: :message_deliverings, source: :recipient
end

app/models/tag.rb
class Tag < ApplicationRecord
  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with gossips table via gossips_meta table
  has_many :gossips, through: :gossip_meta
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :first_name, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

  belongs_to :city
  # 1-N association with gossips table
  has_many :gossips

  # 1-N association with sent_messages (private_messages) table
  # users renamed as senders for this association, class_name explains it to Rails
  has_many :sent_messages, foreign_key: :sender_id, class_name: 'PrivateMessage'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :recipient_id

  # N-N association with received_messages (private_messages) table via the message_deliverings table
  # renamed as recipients but doesn't show here
  has_many :received_messages, through: :message_deliverings

  # 1-N associations with comments
  has_many :comments

  # 1-N associations with likes
  has_many :likes
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  
	def show
		@city=City.find(params[:id])
		@user_id_array=User.where(city_id:params[:id]).pluck(:id)
			   Gossip.all.each do |gossip|
			  if @user_id_array.include?(gossip.user_id)
			  end
		  end
	  end
  
  end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
before_action :authenticate_user

def show 
  @gossip = Gossip.find(params[:id])
  @city = City.find(@gossip.user.city_id)
end


def new
  @gossip = Gossip.new
end


def create 
   @gossip = Gossip.new('title' => params[:title],
                       'content' => params[:content],
                       )
  @gossip.user = current_user
     if @gossip.save # essaie de sauvegarder en base @gossip
        flash[:success] = "Nouveau gossip bien créé !"
       render "welcome/index"
    else
        render "new"
    end
end

def edit 
  @gossip = Gossip.find(params[:id])

end


def update
  @gossip = Gossip.find(params[:id])
  if @gossip.update(title: params[:title],
                    content: params[:content])
    flash[:success] = "Le gossip n°#{@gossip.id} a bien été modifié !"
    render "welcome/index"

  else
    render :edit
  end
end


def destroy 
  @gossip = Gossip.find(params[:id])
  @gossip.destroy
  flash[:danger] = "Le gossip n°#{@gossip.id} a bien été supprimé !"
  render "welcome/index"
end


private

  def authenticate_user
      unless current_user
          flash[:danger] = "Veuillez-vous connecter pour accéder au contenu."
          redirect_to new_session_path
      end
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
 
  def index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  	@city = City.find(@user.city_id)
  end


  def new
  	@user = User.new
  end


  def create 
    @city = City.find_by(name: params[:city_name])
      if @city == nil 
        @city = City.create(name:params[:city_name], zip_code:"53270")
      else

  	@user = User.new('first_name' => params[:first_name],
  									 'last_name' => params[:last_name],
  									 'description' => params[:description],
  									 'age' => params[:age],
  									 'city_id' => City.first.id,
  									 'email' => params[:email],
									   'password' => params[:password_digest])
	  end

	  
		  if @user.save
			log_in(@user)
			flash[:success] = "Inscription réussie ! Vous êtes connecté en tant que #{@user.first_name}"	
  			render "welcome/index"
  		else
  		  render "new"
  		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
    if session[:user_id] != nil
      return true
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<h2 class="h1-responsive font-weight-bold my-5">Bienvenue sur la page d édition du gossip n°<%=@gossip.id%></h2>

<body>
 
   <div class=" border border-light p-5">

     <p class="h4 mb-4">Pour éditer le potin, merci de remplir le formulaire</p>

      <%= form_tag url_for(action: 'update'), method: "patch" do %>
        
        <p><%= label_tag 'Titre du gossip' %></p>
        <%= text_field_tag 'title', value = @gossip.title, class: "form-control mb-4" %>
    
        <p><%= label_tag 'Contenu du gossip' %></p>
        <%= text_field_tag 'content', value = @gossip.content, class: "form-control mb-2"%>
           
           </br>

        <%= submit_tag "Valider", class: "btn btn-primary btn-block" %>

      <% end %>
    </div>


</body>

app/views/gossips/new.html.erb
<h2 class="h1-responsive font-weight-bold my-5">Page de création d un nouveau gossip</h2>

<body>	  
	  <p class="h4 mb-4"> Pour créer un nouveau gossip, merci de remplir le formulaire ci-dessous </p>

	    <%= form_tag url_for(action: 'create'), method: "post" do %>

					<% if @gossip.errors.any? %>
							<div class="alert alert-danger" role="alert">
								  <p>Nous n'avons pas réussi à créer le potin car:</p>
									  <ul>
									    <% @gossip.errors.full_messages.each do |message| %>
									      <li><%= message %></li>
									    <% end %>
									  </ul>
									<% end %>			
							</div>

		      <%= label_tag 'Titre du gossip :' %>
		      <%= text_field_tag(:title)%>
		      </br>
		      <%= label_tag 'Dîtes-nous tout :' %>
		      <%= text_field_tag(:content)%>

		     	</br>
		  
		      <%= submit_tag "Valider" %>

	    <% end %>

</body>

app/views/gossips/show.html.erb
<h2 class="h1-responsive font-weight-bold my-5">Bienvenue sur la page du gossip n°<%= @gossip.id %></h2>

<div class="my-3 p-3 bg-white rounded box-shadow text-success">


    <div class="media text-dark pt-3"> 
      <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">TITRE</strong>
        <%= @gossip.title%>
      </p>
    </div>

    <div class="media text-dark pt-3">  
      <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">CONTENU</strong>
        <%= @gossip.content%>
      </p>
    </div>

    <div class="media text-dark pt-3"> 
      <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">AUTEUR</strong>
          <a> <%= link_to @gossip.user.first_name+" "+@gossip.user.last_name, user_path(@gossip.user_id) %> </a>
      </p>
    </div>

     <div class="media text-dark pt-3"> 
      <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">VILLE</strong>
        <a> <%= link_to @city.name, city_path(@city.id) %> </a>
      </p>
    </div>


  <% if current_user == @gossip.user%>

    <div class="media text-dark pt-3"> 
      <div class="row">
        <div class="pull-left">
            <button type="button" class="btn btn-default btn-lg">
                <span class="glyphicon glyphicon-chevron-left"><p><a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-success">Editer</a></p></span>
             </button>
         </div>
         <div class="pull-right">
            <button type="button" class="btn btn-default btn-lg">
                <span class="glyphicon glyphicon-chevron-right"><p><a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-confirm="Vous êtes bien sûr de vouloir supprimer ce gossip à jamais ?" data-method="DELETE">Supprimer</a></p></span>
            </button>
         </div>
       </div>
     </div>

 <%end%>


</div>

<div style="margin-left: 35px">
  <strong class="d-block text-gray-dark">AJOUTER UN COMMENTAIRE</strong>
</br>
    <%= form_tag gossip_comments_path(@gossip.id), method: "post" do %>
    <%= label_tag 'Ajouter un commentaire :' %>
     <%= text_field_tag(:content)%>
    <%= submit_tag "Valider", class: "btn btn-primary btn" %>
      <% end %>
 </div>

</br>
</br>

<section>
<div class="card-deck">
<%Comment.all.each do |comment|%>
<%if comment.commentable_id == @gossip.id%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Comment #<%=comment.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p>by <%= link_to User.find(comment.user_id).first_name, user_path(User.find(comment.user_id).id)%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%=comment.content%></p>
       </div>
      </footer>
    </blockquote>
  </div>
</div>
</div>
<%end%>
<%end%>
</div>
</section>