config/routes.rb
Rails.application.routes.draw do
  
  resources :cities
  
  resources :team
  
  resources :user
  
  resources :contact
  
  resources :welcome
  
  resources :gossips 
  
  resources :gossips do 
  	resources :comments 
  end
  
  resources :sessions, only:[:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  # 1-N association with users table
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  # 1-N associations with user
  belongs_to :user

  # 1-N polymorphic association with comment and gossip
  belongs_to :commentable, polymorphic: true # can be associated to anything commentable
  has_many :comments, as: :commentable # is something commentable

  # 1-N associations with likes
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title, presence: true, length: {in: 3..50}
  validates :content, presence: true
  
  # 1-N association with users table
  belongs_to :user

  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with tags table via the gossip_meta table
  has_many :tags, through: :gossip_meta

  # 1-N polymorphic association with comments as commentable
  has_many :comments, as: :commentable

  # 1-N associations with likes
  has_many :likes
end

app/models/gossip_metum.rb
# the join table that maps the N-N association between gossips and tags
class GossipMetum < ApplicationRecord
  # 1-N association with gossips table
  belongs_to :gossip

  # 1-N association with tags table
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  # 1-N associations with users, gossips and comments
  belongs_to :user
  # can apply to a gossip or a comment
  belongs_to :gossip, optional: true if :comment_id
  belongs_to :comment, optional: true if :gossip_id
end

app/models/message_delivering.rb
# the join table that maps the N-N association between recipients and received_messages
class MessageDelivering < ApplicationRecord
  # 1-N association with recipients (users) table
  # class_name tells rails recipient is a user
  belongs_to :recipient, class_name: 'User'

  # 1-N association with received_messages (private_messages) table
  # class_name tells rails received_message is a private_message
  belongs_to :received_message, class_name: 'PrivateMessage'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  # 1-N association with senders (users) table
  belongs_to :sender, class_name: 'User'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :received_message_id

  # N-N association with recipients (users) table via message_deliverings table
  has_many :recipients, through: :message_deliverings, source: :recipient
end

app/models/tag.rb
class Tag < ApplicationRecord
  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with gossips table via gossips_meta table
  has_many :gossips, through: :gossip_meta
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :first_name, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

  belongs_to :city
  # 1-N association with gossips table
  has_many :gossips

  # 1-N association with sent_messages (private_messages) table
  # users renamed as senders for this association, class_name explains it to Rails
  has_many :sent_messages, foreign_key: :sender_id, class_name: 'PrivateMessage'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :recipient_id

  # N-N association with received_messages (private_messages) table via the message_deliverings table
  # renamed as recipients but doesn't show here
  has_many :received_messages, through: :message_deliverings

  # 1-N associations with comments
  has_many :comments

  # 1-N associations with likes
  has_many :likes
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
 
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
    if session[:user_id] != nil
      return true
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
    <head>   

      <!-- Bootstrap.com -->
      
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
      <title>The Gossip Project 2019</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
            <!-- Navigation bar-->             
            <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <a class= navbar-text "#fff" <%= link_to "TheGossipProject", welcome_index_path %> </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" text-color = "#fff" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" <%= link_to "Accueil", welcome_index_path %> </a>
            <a class="nav-link"<%= link_to "Equipe", team_index_path %> </a>
            <a class ="nav-link"<%= link_to "Contact",contact_index_path %></a>
          </div>
        </div>

        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" navbar-text "#fff" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Inscription / Connexion
          </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="<%= new_user_path %>">Inscription</a>
              <a class="dropdown-item" href="<%= new_session_path %>">Connexion</a>
              <a class="dropdown-item" <%= link_to "Se déconnecter", session_path(session.id), method: :delete %></a>
            </div>
        </div>
      </nav>
  <%= yield %>
  </body>

 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  
  </html>